name: deploy
on:
  push:
    branches: [ main-pipeline ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Publish
        run: dotnet publish ./RestaurantAPI/RestaurantAPI.csproj -c Release -o ${{ env.DOTNET_ROOT }}/api
      - name: Upload artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: api-artifact
          path: ${{ env.DOTNET_ROOT }}/api
        
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'Dev'
      url: ${{ steps.deploy-to-azure.outputs.webapp-url }}
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: api-artifact
      - name: Azure WebApp deploy
        id: deploy-to-azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 'restaurant-api-app-dg'
          publish-profile: ${{ secrets.PUBLISH_PROFILE_DEV }}
          
